# Generated by Django 4.2.10 on 2024-02-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='img',
            field=models.ImageField(default=2, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
